### ISSUE TITLE
Issues with Logitech Setpoint Keyboards

### ISSUE THREAD

**Issue by xmace** [julianxhokaxhiu/chrome-deezer-mediakeys-reloaded#3]
Dear Julian,

I'm very pleased to use your mediakeys deezer plugin.

Unfortunately, I changed my Keyboard today. Since then the Mediakeys for Deezer are no longer working. Itunes and everything else is still working with the mediakeys.

I found out, that the Setpoint software is using a "players.ini" located in the setpoint installation directory.

Further information:
--> https://forums.logitech.com/t5/Keyboards-and-Keyboard-Mice/SetPoint-PLAYERS-INI-Documentation/td-p/446534

I tryed now many times to add chrome and the Deezer Shortcut Plugin to the players.ini by my own but with no success...

So please are you able to provide the line, which I (and hopefully a lot of other users with the same issue) can add to the players.ini so that the plugin will work again?

like
"iTunes=wac,iTunes.exe,iTunes,xxx,xxx,xxx,xxx,xxx,xxx,xxx,0,1,iTunes"

Thank you very much in advance.

Kind regards,
Matthias

**Comment by julianxhokaxhiu** [comment]
Please follow this link where everything is detailed :)

https://forums.logitech.com/t5/Mice-and-Pointing-Devices/Chrome-MediaKeys-and-Logitech-SetPoint-v6-67-and-older-version/m-p/1430281/highlight/true#M67808
