### ISSUE TITLE
Deezer new UI broke the extension

### ISSUE THREAD

**Issue by Pbroc** [julianxhokaxhiu/chrome-deezer-mediakeys-reloaded#7]
"Error in event handler for runtime.onMessage: TypeError: Cannot read property 'dispatchEvent' of undefined"

Chrome: 69.0.3497.92

**Comment by julianxhokaxhiu** [comment]
Thanks for the report, I'll check back as soon as possible.

**Comment by julianxhokaxhiu** [comment]
New version `1.0.0` published.

You should be able to get it as soon as Google rolls it out ( usually it takes maximum 60 minutes )

**Comment by Pbroc** [comment]
Since the new update it's even worse, when I hit play/pause, the next song start, this is weird.

**Comment by julianxhokaxhiu** [comment]
I did an extensive test on my side and it works just fine. Which OS are you using? And which keyboard ( with software, if any )?

**Comment by Pbroc** [comment]
Windows 10, my keyboard is a Dell with the "Fn" macro + F10 F11 F12 for multimedia, no software for it.

F10 and F12 work fine btw.

**Comment by julianxhokaxhiu** [comment]
Do they come up as Multimedia Keys or just as key combination? Can you please post a screenshot of the keybindings in your Chrome for this extension?

**Comment by Pbroc** [comment]
The keybindings in Chrome show only text for all entry "multimedia content:"

And on my keyboard I have to press/hold in first the "Fn" key then F10 or F11 or F12.

And again, the combination for previous(F10) and next(F12) song work fine.

**Comment by Pbroc** [comment]
Well, a simple reinstallation did the trick apparently, thank you for your time!

I should have try that first...

**Comment by julianxhokaxhiu** [comment]
All fine :) Glad it worked!
